Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo_Booking_Lessons_For_Driving.Controllers
{
    public class HomeController : Controller
    {
    
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
        [Authorize]
        public ActionResult LandingPage()
        {
            return View();
        }
    }
}

Controllers/LearnerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Demo_Booking_Lessons_For_Driving.Models;
namespace Demo_Booking_Lessons_For_Driving.Controllers
{
    public class LearnerController : Controller
    {
        Dictionary<string, int> gList = new Dictionary<string, int>();
        DbEntities DbEntities = new DbEntities();

        // GET: Learner
        [Authorize]
        public ActionResult Book()
        {
            GetTypeOfVehicle();
            GetgategoryLicences();
            LoadProvincesOnView();
            return View();
        }
        [HttpPost]
        public ActionResult Book(Learner learner)
        {
           
            GetgategoryLicences();
            LoadProvincesOnView();
            GetTypeOfVehicle();
            if (ModelState.IsValid)
            {
              var _Learner =  DbEntities.Learners.Find(learner.IDNumber);
               if(_Learner == null)
                {
                DbEntities.Learners.Add(learner);
                DbEntities.SaveChanges();
                ViewBag.Message = "Your bookings have been successfully scheduled!!";
                ViewBag.Status = true;
                return RedirectToAction("Pay","Card",learner);
                }
               else
                {
                    
                    ViewBag.Message = "User Already Exist check your status";
                }
              
            }
            else
            {
                ViewBag.Message = "Oops Something went wrong!!";
                ViewBag.Status = false;
            }
            return View();
        }
        [HttpGet]
        public ActionResult ViewBookings()
        {
            List<Learner> learners = DbEntities.Learners.ToList();
            ViewBag.Learners = learners;
            return View(ViewBag.Learners);
        }
        public ActionResult SelectProvince()
        {
            return View();
        }


        public void LoadProvincesOnView()
        {
            var list = new List<string>();
            list.Add("Free State");
            list.Add("Gauteng");
            list.Add("Kwazulu-Natal");
            list.Add("Limpopo");
            list.Add("North-West");
            list.Add("Eastern Cape");
            list.Add("Northern Cape");
            list.Add("Mpumalanga");
            list.Add("WesternCape");
            ViewBag.Province = list;
        }
        public void GetgategoryLicences()
{
gList.Clear();
            gList.Add("Driver's licence for motor cycle", 3);
            gList.Add("Driver's licence for light motor vehicle", 4);
            gList.Add("Driver's licence for heavy Motor vehicle ", 5);
            ViewBag.Gategories = gList;
        }


        public void GetTypeOfVehicle()
        {
            var list = new List<string>();
            list.Add("A-Motor Cycle,Exceeding 125 CM3");
            list.Add("B- Motor Vehicle,Not Exceeding 3500KG," +
                "EB- Articulated MV,Not Exceeding 3500kg");

            list.Add("A-Motor Cycle,Exceeding 125 CM3");
            list.Add("C-Motor Vehicle,Exceeding 1600..C1- Motor vehicle ,3500KG-16000KG," +
                " EC - Articulated MV Exceeding 16000KG." + "EC1-Articulated MV,3500 KG -16000Kg");

            ViewBag.Descriptions = list;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveModifiedChanges(Learner learner)
        {
            try
            {
              DbEntities.Entry(learner).State = System.Data.Entity.EntityState.Modified;
            DbEntities.SaveChanges();
           
            }catch(Exception e)
            {

            }
            return RedirectToAction("ViewBookings");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<!--Grid row-->
<div class="row">

    <!--Grid column-->
    <div class="col-md-6 mb-4">

        <!--Card-->
        <div class="card card-cascade narrower">

            <!--Card image-->
            <div class="view view-cascade gradient-card-header blue-gradient">
                <h5 class="mb-0">About Car Hub</h5>
            </div>
            <!--/Card image-->
            <!--Card content-->
            <div class="card-body card-body-cascade text-center">

                <div class="jumbotron">
                    <h2>How Car Hub Works </h2>
                    <div class="lead">
                        <p> 1. Find the perfect ride</p>

                        <p> 2. Book the location and time.</p>

                        <p>3. Pay and confirm booking.</p>

                        <p>4. Enjoy your lesson and come back to review!</p>

                    </div>
                </div>


            </div>
            <!--/.Card content-->

        </div>
        <!--/.Card-->

    </div>
    <!--Grid column-->
    <!--Grid column-->
    <div class="col-md-6 mb-4">

        <!--Card-->
        <div class="card card-cascade narrower">

            <!--Card image-->
            <div class="view view-cascade gradient-card-header peach-gradient">
                <h5 class="mb-0">Map</h5>
            </div>
            <!--/Card image-->
            <!--Card content-->
            <div class="card-body card-body-cascade text-center">

                <!--Google map-->
                <div id="map-container-google-8" class="z-depth-1-half map-container-5" style="height: 300px">
                    <iframe src="https://maps.google.com/maps?q=Barcelona&t=&z=13&ie=UTF8&iwloc=&output=embed"
                            frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>


            </div>
            <!--/.Card content-->

        </div>
        <!--/.Card-->

    </div>
    <!--Grid column-->

</div>
<!--Grid row-->

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Car Hub", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Login", "Login", "Employee")</li>
                <li>@Html.ActionLink("Registration", "Registration", "Employee")</li>
            </ul>
        </div>
    </div>
</div>
<!-- Background Video-->
<div class="container ">
    <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop"><source src="~/Content/assets/mp4/bg.mp4" type="video/mp4" /></video>
</div>

Views/Home/LandingPage.cshtml
@{
    ViewBag.Title = "LandingPage";
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Car Hub", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav  navbar-right ">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @if (Request.IsAuthenticated)
                            {
                                @HttpContext.Current.User.Identity.Name
                            }
           

                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (Request.IsAuthenticated)
                            {

                                using (Html.BeginForm("Logout", "Employee", FormMethod.Post))
                                {
                                    <a href="javascript:document.getElementById('logoutForm').submit()" style="width:100%;color:red;text-align:left; display:block;">Logout</a>
                                }
                            }
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>


<div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar">
       
        <ul class="list-unstyled components">

            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                    <li>@Html.ActionLink("Logout", "Index", "Home")</li>

                    <li>
                        <a href="#">Home 2</a>
                    </li>
                    <li>
                        <a href="#">Home 3</a>
                    </li>
                </ul>
            </li>

            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">View Data</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        @Html.ActionLink("View Bookings", "ViewBookings", "Learner")
                    </li>
                    <li>
                        @Html.ActionLink("View Instructors", "ViewInstructors", "Employee")
                    </li>
                    <li>
                        @Html.ActionLink("View Employees", "ViewEmployees", "Employee")
                    </li>

                </ul>
            </li>
            <li>      
                @Html.ActionLink("Book", "Book", "Learner")
            </li>
            <li>
                <a href="#">Contact</a>
            </li>
        </ul>

    </nav>
    
</div>